name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake for Dark Mode
        uses: Platane/snk@v3
        with:
          github_user_name: ValentinTarantino
          outputs: dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to repo
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: main
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
